In [1]:
import numpy as np
import math
import os
import time
import threading
from pymycobot.mycobot280 import MyCobot280
from pymycobot.genre import Angle, Coord

In [5]:
mc = MyCobot280('/dev/ttyJETCOBOT', 1000000)
mc.thread_lock = True
print("로봇이 연결되었습니다.")

로봇이 연결되었습니다.


In [9]:
home_angles = [0.17, -34.18, 0.52, -40.86, 6.5, -40.16] # 초기 위치 (각도 단위)
# home_angles = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # 초기 위치 (좌표 단위)
speed = 10
mc.send_angles(home_angles, speed)
print("로봇이 홈 위치로 이동했습니다.")
mc.set_gripper_value(100, speed) # 그리퍼 열기 # 닫기는 0
print("로봇이 그리퍼를 열었습니다.")
time.sleep(3) # 움직임이 완료될 때까지 대기

# 현재 각도 읽기
angles = mc.get_angles()
print("현재 각도:", angles) # [0.08, -12.91, 0.52, -41.92, 3.6, -42.18] # [0.17, -34.18, 0.52, -40.86, 6.5, -40.16] 
# 현재 좌표 읽기
coords = mc.get_coords()
print("현재 좌표:", coords)
# 인코더 값 읽기
encoders = mc.get_encoders()
print("인코더:", encoders)
# 라디안 값 읽기
radians = mc.get_radians()
print("라디안:", radians)

로봇이 홈 위치로 이동했습니다.
로봇이 그리퍼를 열었습니다.
현재 각도: [-0.08, -33.66, 0.7, -40.86, 6.41, -39.72]
현재 좌표: [197.0, -59.4, 277.6, -163.49, -5.47, -50.24]
인코더: [2049, 2431, 2056, 2513, 1975, 2500]
라디안: [-0.001, -0.587, 0.012, -0.713, 0.112, -0.693]


In [7]:
# 현재 좌표 읽기
coords = mc.get_coords()
print("현재 좌표:", coords)

현재 좌표: [193.3, -59.3, 247.0, -179.2, 3.94, -46.26]


In [8]:
# 만약 degrees라면 radians로 변환
rx_rad = math.radians(coords[3])
ry_rad = math.radians(coords[4])
rz_rad = math.radians(coords[5])

def euler_to_rotmat(roll, pitch, yaw):
    R_x = np.array([
        [1, 0, 0],
        [0, np.cos(roll), -np.sin(roll)],
        [0, np.sin(roll), np.cos(roll)]
    ])

    R_y = np.array([
        [np.cos(pitch), 0, np.sin(pitch)],
        [0, 1, 0],
        [-np.sin(pitch), 0, np.cos(pitch)]
    ])

    R_z = np.array([
        [np.cos(yaw), -np.sin(yaw), 0],
        [np.sin(yaw), np.cos(yaw), 0],
        [0, 0, 1]
    ])

    return R_z @ R_y @ R_x

rot_matrix = euler_to_rotmat(rx_rad, ry_rad, rz_rad)

print("TCP 회전 행렬:")
print(rot_matrix)


TCP 회전 행렬:
[[ 0.68975291 -0.72307751 -0.03741434]
 [-0.72077709 -0.69062645  0.05929164]
 [-0.06871179 -0.01392918 -0.99753931]]


TCP 회전 행렬:
[[ 0.64175889, -0.71973299,  0.2648206 ]
 [-0.76157347, -0.63874723,  0.10958019]
 [ 0.09028495, -0.27200441, -0.95805127]]

[[ 0.68975291, -0.72307751, -0.03741434]
 [-0.72077709, -0.69062645,  0.05929164]
 [-0.06871179, -0.01392918, -0.99753931]]